### ISSUE TITLE
Hi Ritchie!

### ISSUE THREAD

**Issue by tzjg7293** [rsmacapinlac/dots#1]
Hi Ritchie, I know this may be a long shot and I hope you don't find it uncomfortable with me reaching out to you as a GitHub issue. But my name is Sydney and I am reaching out after our meeting at the West Coast Virtual Fairs 2023 on May 17.  I was the woman whom you told an (amazing) sales pitch to, and I told you about my motto of “Efficiency” and how I automated my whole MacBook laptop since I believe humans should not spend their one and only life doing repetitive tasks. I had sent you two emails (one follow-up) after our meeting but I didn't receive any response so I am worried that perhaps my email was filtered out because it contained an attachment (my resume).

My email is Sydney.tj.fang@gmail.com and once again I apologise for scaring you like this!

**Comment by rsmacapinlac** [comment]
No worries Sydney. I've replied on LinkedIn.
